spring:
  profile:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/college
    username: college
    password: college123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
  # Server configuration
server:
  port: 7000 #set your port

  flyway:
    baseline-on-migrate: true
    enable: true
    schemas: college
    #url: jdbc:postgresql://localhost:5432/college
    username: college
    password: college123
    baseline-description: "init"
    baseline-version: 0


security:
  jwt:
    token-secret-key: 3777217A25432A462D4A614E645267556B586E3272357538782F413F4428472B
    refresh-token-expiration: 2800000
    expiration: 900000000